version: '3.0'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=file:./dev.db
    volumes: 
      - .:/usr/app