version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://root:root@database:5432/saudeclub?schema=public
    volumes: 
      - .:/usr/app
    depends_on:
      - database

  database:
    container_name: database
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: saudeclub
    ports:
      - 5432:5432